name: Build Nico3DSStream

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install devkitPro
        run: |
          wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
          sudo dpkg -i devkitpro-pacman.deb
          dkp-pacman -S switch-dev
          echo "export DEVKITPRO=/opt/devkitPro" >> $GITHUB_ENV
          echo "export DEVKITARM=${DEVKITPRO}/devkitARM" >> $GITHUB_ENV
          echo "export DEVKITPPC=${DEVKITPRO}/devkitPPC" >> $GITHUB_ENV
          echo "export PATH=$PATH:${DEVKITPRO}/tools/bin" >> $GITHUB_ENV

      - name: Clone Libraries
        run: |
          git clone https://github.com/devkitPro/ctru.git /tmp/ctru
          git clone https://github.com/devkitPro/sf2dlib.git /tmp/sf2dlib
          git clone https://github.com/devkitPro/citro3d.git /tmp/citro3d

      - name: Build .3dsx
        run: |
          cd source
          make
          mkdir -p ../build
          cp Nico3DSStream.3dsx ../build/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nico3DSStream-3dsx
          path: build/Nico3DSStream.3dsx
